/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isica
 */
public class UsuarioEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioEmpleado
     */
    public UsuarioEmpleado(String datos) {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) productosSinStock.getModel();
        String[] arr = datos.split("\n");
        
        for(int i = 0;i< arr.length;i++){
            System.out.println(arr[i]);
            String[] data = arr[i].split(",");
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosSinStock = new javax.swing.JTable();
        botonAgregarStock = new javax.swing.JButton();
        botonVolverUsuarioEmpleado = new javax.swing.JButton();
        tituloUsuarioEmpleado = new javax.swing.JLabel();
        textoCodigoEmpleado = new javax.swing.JLabel();
        textoRutEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productosSinStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productosSinStock.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(productosSinStock);

        botonAgregarStock.setText("Agregar Stock");

        botonVolverUsuarioEmpleado.setText("Volver");

        tituloUsuarioEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloUsuarioEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloUsuarioEmpleado.setText("Menu de usuario");

        textoCodigoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoCodigoEmpleado.setText("Codgio:");

        textoRutEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRutEmpleado.setText("Rut:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolverUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarStock)
                .addGap(22, 22, 22))
            .addComponent(tituloUsuarioEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoRutEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textoCodigoEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloUsuarioEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoRutEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCodigoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarStock)
                    .addComponent(botonVolverUsuarioEmpleado))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonAgregarStock() {
        return botonAgregarStock;
    }

    public JButton getBotonVolverUsuarioEmpleado() {
        return botonVolverUsuarioEmpleado;
    }

    public JTable getProductosSinStock() {
        return productosSinStock;
    }

    public JLabel getTextoCodigoEmpleado() {
        return textoCodigoEmpleado;
    }

    public JLabel getTextoRutEmpleado() {
        return textoRutEmpleado;
    }

    public JLabel getTituloUsuarioEmpleado() {
        return tituloUsuarioEmpleado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarStock;
    private javax.swing.JButton botonVolverUsuarioEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productosSinStock;
    private javax.swing.JLabel textoCodigoEmpleado;
    private javax.swing.JLabel textoRutEmpleado;
    private javax.swing.JLabel tituloUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
