package ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author marti
 */
public class VentanaUsuarioEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEmpleadoInfo
     */
    public VentanaUsuarioEmpleado() {
        initComponents();
    }

    public JLabel getBotonCorreoDatos() {
        return botonCorreoDatos;
    }

    public JLabel getBotonNombreDatos() {
        return botonNombreDatos;
    }

    public JLabel getBotonRutDatos() {
        return botonRutDatos;
    }

    public JButton getBotonVolverDatos() {
        return botonVolverDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVovlerHistorial = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        botonNombreDatos = new javax.swing.JLabel();
        botonRutDatos = new javax.swing.JLabel();
        botonCorreoDatos = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        botonVolverDatos = new javax.swing.JButton();

        botonVovlerHistorial.setText("Volver");
        botonVovlerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVovlerHistorialActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonNombreDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonNombreDatos.setText("Nombre: ");

        botonRutDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRutDatos.setText("Rut: ");

        botonCorreoDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCorreoDatos.setText("Correo:");

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Datos del empleado");

        botonVolverDatos.setText("Volver");
        botonVolverDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCorreoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRutDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(botonVolverDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(titulo)
                .addGap(37, 37, 37)
                .addComponent(botonNombreDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRutDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCorreoDatos)
                .addGap(40, 40, 40)
                .addComponent(botonVolverDatos)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVovlerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVovlerHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVovlerHistorialActionPerformed

    private void botonVolverDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCorreoDatos;
    private javax.swing.JLabel botonNombreDatos;
    private javax.swing.JLabel botonRutDatos;
    private javax.swing.JButton botonVolverDatos;
    private javax.swing.JButton botonVovlerHistorial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
