/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JButton;

/**
 *
 * @author isica
 */
public class VentanaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscar
     */
    public VentanaBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscarNombre = new javax.swing.JButton();
        botonBuscarCategoria = new javax.swing.JButton();
        botonBuscarPrecio = new javax.swing.JButton();
        botonBuscarOfertas = new javax.swing.JButton();
        botonBuscarCodigo = new javax.swing.JButton();
        botonVolverMenuBuscar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonBuscarNombre.setText("Buscar por nombre");

        botonBuscarCategoria.setText("Buscar por categoria");

        botonBuscarPrecio.setText("Buscar por precio");

        botonBuscarOfertas.setText("Buscar por ofertas");

        botonBuscarCodigo.setText("Buscar por codigo");

        botonVolverMenuBuscar.setText("Volver");
        botonVolverMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuBuscarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Menu Buscar Por");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverMenuBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(botonBuscarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarOfertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarCodigo)
                .addGap(5, 5, 5)
                .addComponent(botonVolverMenuBuscar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonBuscarCategoria(){
        return botonBuscarCategoria;
    }
    public JButton getBotonBuscarNombre(){
        return botonBuscarNombre;
    }
    public JButton getBotonBuscarCodigo(){
        return botonBuscarCodigo;
    }
    public JButton getBotonBuscarPrecio(){
        return botonBuscarPrecio;
    }
    public JButton getBotonBuscarOfertas(){
        return botonBuscarOfertas;
    }
    public JButton getBotonVolverMenuBuscar(){
        return botonVolverMenuBuscar;
    }
    
    private void botonVolverMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuBuscarActionPerformed

    }//GEN-LAST:event_botonVolverMenuBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCategoria;
    private javax.swing.JButton botonBuscarCodigo;
    private javax.swing.JButton botonBuscarNombre;
    private javax.swing.JButton botonBuscarOfertas;
    private javax.swing.JButton botonBuscarPrecio;
    private javax.swing.JButton botonVolverMenuBuscar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
