/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isica
 */
public class VentanaCarrito extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCarrito
     */
    public VentanaCarrito(String datos) {
        initComponents();
        
        String[] arr = datos.split("\n");
        DefaultTableModel model = (DefaultTableModel) listaCompras.getModel();
        
        for(int i = 0;i<arr.length;i++){
            String[] data = arr[i].split(",");
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVovlerCarrito = new javax.swing.JButton();
        botonEliminarCarrito = new javax.swing.JButton();
        comprarTexto = new javax.swing.JLabel();
        totalTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCompras = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        botonComprarCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonVovlerCarrito.setText("Volver");
        botonVovlerCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVovlerCarritoActionPerformed(evt);
            }
        });

        botonEliminarCarrito.setText("Eliminar");

        comprarTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comprarTexto.setText("Total:");

        totalTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        listaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listaCompras);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Carrito de compras");

        botonComprarCarrito.setText("Comprar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVovlerCarrito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comprarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonEliminarCarrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonComprarCarrito))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comprarTexto)
                    .addComponent(totalTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarCarrito)
                    .addComponent(botonComprarCarrito)
                    .addComponent(botonVovlerCarrito))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVovlerCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVovlerCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVovlerCarritoActionPerformed

    public JButton getBotonComprarCarrito() {
        return botonComprarCarrito;
    }

    public JButton getBotonVovlerCarrito() {
        return botonVovlerCarrito;
    }

    public JTable getListaCompras() {
        return listaCompras;
    }

    public JLabel getTotalTexto() {
        return totalTexto;
    }

    public JButton getBotonEliminarCarrito() {
        return botonEliminarCarrito;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprarCarrito;
    private javax.swing.JButton botonEliminarCarrito;
    private javax.swing.JButton botonVovlerCarrito;
    private javax.swing.JLabel comprarTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaCompras;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel totalTexto;
    // End of variables declaration//GEN-END:variables
}
