/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isica
 */
public class VentanaListar_Modificar_Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListar
     */
    public VentanaListar_Modificar_Eliminar(String datos) {
        
        initComponents();
        
        String[] arr = datos.split("\n");
        DefaultTableModel model = (DefaultTableModel) listaProductos.getModel();
        
        for(int i = 0;i<arr.length;i++){
            String[] data = arr[i].split(",");
            model.addRow(data);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JTable();
        botonVolverVentanaListar = new javax.swing.JButton();
        botonEliminarVentanaListar = new javax.swing.JButton();
        botonModificarVentanaListar = new javax.swing.JButton();
        barraBuscarListar_Modificar_Eliminar = new javax.swing.JTextField();
        botonBuscarVentanaListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Lista Productos");

        listaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaProductos.setToolTipText("");
        listaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(listaProductos);

        botonVolverVentanaListar.setText("Volver");

        botonEliminarVentanaListar.setText("Eliminar");
        botonEliminarVentanaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarVentanaListarActionPerformed(evt);
            }
        });

        botonModificarVentanaListar.setText("Modifcar");
        botonModificarVentanaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarVentanaListarActionPerformed(evt);
            }
        });

        barraBuscarListar_Modificar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBuscarListar_Modificar_EliminarActionPerformed(evt);
            }
        });

        botonBuscarVentanaListar.setText("Buscar");
        botonBuscarVentanaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVentanaListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonBuscarVentanaListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraBuscarListar_Modificar_Eliminar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonVolverVentanaListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarVentanaListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarVentanaListar)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraBuscarListar_Modificar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarVentanaListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarVentanaListar)
                    .addComponent(botonModificarVentanaListar)
                    .addComponent(botonVolverVentanaListar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarVentanaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarVentanaListarActionPerformed

    }//GEN-LAST:event_botonEliminarVentanaListarActionPerformed

    private void botonModificarVentanaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarVentanaListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarVentanaListarActionPerformed

    private void barraBuscarListar_Modificar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBuscarListar_Modificar_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBuscarListar_Modificar_EliminarActionPerformed

    private void botonBuscarVentanaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVentanaListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarVentanaListarActionPerformed
    
    public JButton getBotonVolverVentanaListar(){
        return botonVolverVentanaListar;
    }
    public JButton getBotonEliminarVentanaListar(){
        return botonEliminarVentanaListar;
    }
    public JButton getBotonModificarVentanaListar(){
        return botonModificarVentanaListar;
    }
    public JTextField getBarraBuscarVentanaListar(){
        return barraBuscarListar_Modificar_Eliminar;
    }
    public JButton getBotonBuscarVentanaListar(){
        return botonBuscarVentanaListar;
    }
    public JTable getListTable(){
        return listaProductos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barraBuscarListar_Modificar_Eliminar;
    private javax.swing.JButton botonBuscarVentanaListar;
    private javax.swing.JButton botonEliminarVentanaListar;
    private javax.swing.JButton botonModificarVentanaListar;
    private javax.swing.JButton botonVolverVentanaListar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaProductos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
