package ventanas;

import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isica
 */
public class VentanaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerente
     */
    public VentanaEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAgregar = new javax.swing.JButton();
        botonListar_Modificar_Eliminar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        botonVolverMenuEmpleado = new javax.swing.JButton();
        botonUsuarioEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        botonAgregar.setText("Agregar ");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonListar_Modificar_Eliminar.setText("Listar/Eliminar/Modificar");
        botonListar_Modificar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListar_Modificar_EliminarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Opciones de Empleado");

        botonVolverMenuEmpleado.setText("Volver");
        botonVolverMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverMenuEmpleadoActionPerformed(evt);
            }
        });

        botonUsuarioEmpleado.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonListar_Modificar_Eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolverMenuEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonUsuarioEmpleado)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonUsuarioEmpleado)
                .addGap(42, 42, 42)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(botonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonListar_Modificar_Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVolverMenuEmpleado)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotonAgregar(){
        return botonAgregar;
    }
    public JButton getBotonListar_Modificar_Eliminar(){
        return botonListar_Modificar_Eliminar;
    }
    public JButton getBotonVolver(){
        return botonVolverMenuEmpleado;
    }

    public JButton getBotonUsuarioEmpleado() {
        return botonUsuarioEmpleado;
    }
    
    
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed

    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonVolverMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuEmpleadoActionPerformed

    }//GEN-LAST:event_botonVolverMenuEmpleadoActionPerformed

    private void botonListar_Modificar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListar_Modificar_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListar_Modificar_EliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonListar_Modificar_Eliminar;
    private javax.swing.JButton botonUsuarioEmpleado;
    private javax.swing.JButton botonVolverMenuEmpleado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
