/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isica
 */
public class VentanaUsuarioCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuarioCliente
     */
    public VentanaUsuarioCliente(String datos) {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) listaHistorial.getModel();
        String[] arr = datos.split("\n");
        
        for(int i = 0;i< arr.length;i++){
            String[] data = arr[i].split(",");
            model.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        botonVovlerHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaHistorial = new javax.swing.JTable();
        textoRutCliente = new javax.swing.JLabel();
        textoHistorial = new javax.swing.JLabel();
        textoEmailCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Menu de usuario");

        botonVovlerHistorial.setText("Volver");
        botonVovlerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVovlerHistorialActionPerformed(evt);
            }
        });

        listaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaHistorial.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(listaHistorial);

        textoRutCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoRutCliente.setText("Rut:");

        textoHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoHistorial.setText("Historial de compras");

        textoEmailCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textoEmailCliente.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonVovlerHistorial)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(textoRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoHistorial))
                        .addComponent(textoEmailCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoEmailCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoHistorial)
                    .addComponent(textoRutCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonVovlerHistorial)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVovlerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVovlerHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVovlerHistorialActionPerformed

    public JButton getBotonVovlerHistorial() {
        return botonVovlerHistorial;
    }

    public JTable getListaHistorial() {
        return listaHistorial;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public JLabel getTextoRutCliente() {
        return textoRutCliente;
    }

    public JLabel getTextoEmailCliente() {
        return textoEmailCliente;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVovlerHistorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaHistorial;
    private javax.swing.JLabel textoEmailCliente;
    private javax.swing.JLabel textoHistorial;
    private javax.swing.JLabel textoRutCliente;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
